# Generated by Django 3.0.8 on 2020-09-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20200912_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
