# Generated by Django 3.0.8 on 2020-09-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_buynow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyNow',
        ),
    ]
