# Generated by Django 3.0.8 on 2020-09-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_addcart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='user',
        ),
    ]
